<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateGeoCountry extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('geo_country', function (Blueprint $table) {
            $table->id('country_id');
            $table->string('country_title');
            $table->string('code');
            $table->integer('first');
            $table->integer('hidden');
            $table->timestamps();
        });


        // Insert some stuff
        $this->insertSqlData();



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('geo_country');
    }



    public function insertSqlData(){
        $sql = "INSERT INTO geo_country (`country_id`, `country_title`, `code`, `first`, `hidden`) VALUES
        (1, 'Afghanistan', 'AF', 0, 0),
        (2, 'Aland Islands', 'AX', 0, 0),
        (3, 'Albania', 'AL', 0, 0),
        (4, 'Algeria', 'DZ', 0, 0),
        (5, 'American Samoa', 'AS', 0, 0),
        (6, 'Andorra', 'AD', 0, 0),
        (7, 'Angola', 'AO', 0, 0),
        (8, 'Anguilla', 'AI', 0, 0),
        (10, 'Antigua and Barbuda', 'AG', 0, 0),
        (11, 'Argentina', 'AR', 0, 0),
        (12, 'Armenia', 'AM', 0, 0),
        (13, 'Aruba', 'AW', 0, 0),
        (14, 'Australia', 'AU', 0, 0),
        (15, 'Austria', 'AT', 0, 0),
        (16, 'Azerbaijan', 'AZ', 0, 0),
        (17, 'Bahamas', 'BS', 0, 0),
        (18, 'Bahrain', 'BH', 0, 0),
        (19, 'Bangladesh', 'BD', 0, 0),
        (20, 'Barbados', 'BB', 0, 0),
        (21, 'Belarus', 'BY', 0, 0),
        (22, 'Belgium', 'BE', 0, 0),
        (23, 'Belize', 'BZ', 0, 0),
        (24, 'Benin', 'BJ', 0, 0),
        (25, 'Bermuda', 'BM', 0, 0),
        (26, 'Bhutan', 'BT', 0, 0),
        (27, 'Bolivia, Plurinational State of', 'BO', 0, 0),
        (29, 'Bosnia and Herzegovina', 'BA', 0, 0),
        (30, 'Botswana', 'BW', 0, 0),
        (31, 'Brazil', 'BR', 0, 0),
        (32, 'British Indian Ocean Territory', 'IO', 0, 0),
        (33, 'Brunei Darussalam', 'BN', 0, 0),
        (34, 'Bulgaria', 'BG', 0, 0),
        (35, 'Burkina Faso', 'BF', 0, 0),
        (36, 'Burundi', 'BI', 0, 0),
        (37, 'Cabo Verde', 'CV', 0, 0),
        (38, 'Cambodia', 'KH', 0, 0),
        (39, 'Cameroon', 'CM', 0, 0),
        (40, 'Canada', 'CA', 1, 0),
        (41, 'Cayman Islands', 'KY', 0, 0),
        (42, 'Central African Republic', 'CF', 0, 0),
        (43, 'Chad', 'TD', 0, 0),
        (44, 'Chile', 'CL', 0, 0),
        (45, 'China', 'CN', 0, 0),
        (46, 'Christmas Island', 'CX', 0, 0),
        (47, 'Colombia', 'CO', 0, 0),
        (48, 'Comoros', 'KM', 0, 0),
        (49, 'Congo', 'CG', 0, 0),
        (50, 'Congo, The Democratic Republic of The', 'CD', 0, 0),
        (51, 'Cook Islands', 'CK', 0, 0),
        (52, 'Costa Rica', 'CR', 0, 0),
        (53, 'Cote D\'ivoire', 'CI', 0, 0),
        (54, 'Croatia', 'HR', 0, 0),
        (55, 'Cuba', 'CU', 0, 0),
        (57, 'Cyprus', 'CY', 0, 0),
        (58, 'Czech Republic', 'CZ', 0, 0),
        (59, 'Denmark', 'DK', 0, 0),
        (60, 'Djibouti', 'DJ', 0, 0),
        (61, 'Dominica', 'DM', 0, 0),
        (62, 'Dominican Republic', 'DO', 0, 0),
        (63, 'Ecuador', 'EC', 0, 0),
        (64, 'Egypt', 'EG', 0, 0),
        (65, 'El Salvador', 'SV', 0, 0),
        (66, 'Equatorial Guinea', 'GQ', 0, 0),
        (67, 'Eritrea', 'ER', 0, 0),
        (68, 'Estonia', 'EE', 0, 0),
        (69, 'Ethiopia', 'ET', 0, 0),
        (70, 'Falkland Islands (Malvinas)', 'FK', 0, 0),
        (71, 'Faroe Islands', 'FO', 0, 0),
        (72, 'Fiji', 'FJ', 0, 0),
        (73, 'Finland', 'FI', 0, 0),
        (74, 'France', 'FR', 0, 0),
        (75, 'French Guiana', 'GF', 0, 0),
        (76, 'French Polynesia', 'PF', 0, 0),
        (77, 'French Southern Territories', 'TF', 0, 0),
        (78, 'Gabon', 'GA', 0, 0),
        (79, 'Gambia', 'GM', 0, 0),
        (80, 'Georgia', 'GE', 0, 0),
        (81, 'Germany', 'DE', 0, 0),
        (82, 'Ghana', 'GH', 0, 0),
        (83, 'Gibraltar', 'GI', 0, 0),
        (84, 'Greece', 'GR', 0, 0),
        (85, 'Greenland', 'GL', 0, 0),
        (86, 'Grenada', 'GD', 0, 0),
        (87, 'Guadeloupe', 'GP', 0, 0),
        (88, 'Guam', 'GU', 0, 0),
        (89, 'Guatemala', 'GT', 0, 0),
        (90, 'Guernsey', 'GG', 0, 0),
        (91, 'Guinea', 'GN', 0, 0),
        (92, 'Guinea-Bissau', 'GW', 0, 0),
        (93, 'Guyana', 'GY', 0, 0),
        (94, 'Haiti', 'HT', 0, 0),
        (95, 'Holy See', 'VA', 0, 0),
        (96, 'Honduras', 'HN', 0, 0),
        (97, 'Hong Kong', 'HK', 0, 0),
        (98, 'Hungary', 'HU', 0, 0),
        (99, 'Iceland', 'IS', 0, 0),
        (100, 'India', 'IN', 0, 0),
        (101, 'Indonesia', 'ID', 0, 0),
        (102, 'Iran, Islamic Republic of', 'IR', 0, 0),
        (103, 'Iraq', 'IQ', 0, 0),
        (104, 'Ireland', 'IE', 0, 0),
        (105, 'Isle of Man', 'IM', 0, 0),
        (106, 'Israel', 'IL', 0, 0),
        (107, 'Italy', 'IT', 0, 0),
        (108, 'Jamaica', 'JM', 0, 0),
        (109, 'Japan', 'JP', 0, 0),
        (110, 'Jersey', 'JE', 0, 0),
        (111, 'Jordan', 'JO', 0, 0),
        (112, 'Kazakhstan', 'KZ', 0, 0),
        (113, 'Kenya', 'KE', 0, 0),
        (114, 'Kiribati', 'KI', 0, 0),
        (115, 'Korea, Democratic People\'s Republic of', 'KP', 0, 0),
        (116, 'Korea, Republic of', 'KR', 0, 0),
        (117, 'Kuwait', 'KW', 0, 0),
        (118, 'Kyrgyzstan', 'KG', 0, 0),
        (119, 'Lao People\'s Democratic Republic', 'LA', 0, 0),
        (120, 'Latvia', 'LV', 0, 0),
        (121, 'Lebanon', 'LB', 0, 0),
        (122, 'Lesotho', 'LS', 0, 0),
        (123, 'Liberia', 'LR', 0, 0),
        (124, 'Libya', 'LY', 0, 0),
        (125, 'Liechtenstein', 'LI', 0, 0),
        (126, 'Lithuania', 'LT', 0, 0),
        (127, 'Luxembourg', 'LU', 0, 0),
        (128, 'Macao', 'MO', 0, 0),
        (129, 'Macedonia, The Former Yugoslav Republic of', 'MK', 0, 0),
        (130, 'Madagascar', 'MG', 0, 0),
        (131, 'Malawi', 'MW', 0, 0),
        (132, 'Malaysia', 'MY', 0, 0),
        (133, 'Maldives', 'MV', 0, 0),
        (134, 'Mali', 'ML', 0, 0),
        (135, 'Malta', 'MT', 0, 0),
        (136, 'Marshall Islands', 'MH', 0, 0),
        (137, 'Martinique', 'MQ', 0, 0),
        (138, 'Mauritania', 'MR', 0, 0),
        (139, 'Mauritius', 'MU', 0, 0),
        (140, 'Mayotte', 'YT', 0, 0),
        (141, 'Mexico', 'MX', 0, 0),
        (142, 'Micronesia, Federated States of', 'FM', 0, 0),
        (143, 'Moldova, Republic of', 'MD', 0, 0),
        (144, 'Monaco', 'MC', 0, 0),
        (145, 'Mongolia', 'MN', 0, 0),
        (146, 'Montenegro', 'ME', 0, 0),
        (147, 'Montserrat', 'MS', 0, 0),
        (148, 'Morocco', 'MA', 0, 0),
        (149, 'Mozambique', 'MZ', 0, 0),
        (150, 'Myanmar', 'MM', 0, 0),
        (151, 'Namibia', 'NA', 0, 0),
        (152, 'Nauru', 'NR', 0, 0),
        (153, 'Nepal', 'NP', 0, 0),
        (154, 'Netherlands', 'NL', 0, 0),
        (155, 'New Caledonia', 'NC', 0, 0),
        (156, 'New Zealand', 'NZ', 0, 0),
        (157, 'Nicaragua', 'NI', 0, 0),
        (158, 'Niger', 'NE', 0, 0),
        (159, 'Nigeria', 'NG', 0, 0),
        (160, 'Niue', 'NU', 0, 0),
        (161, 'Norfolk Island', 'NF', 0, 0),
        (162, 'Northern Mariana Islands', 'MP', 0, 0),
        (163, 'Norway', 'NO', 0, 0),
        (164, 'Oman', 'OM', 0, 0),
        (165, 'Pakistan', 'PK', 0, 0),
        (166, 'Palau', 'PW', 0, 0),
        (167, 'Palestine, State of', 'PS', 0, 0),
        (168, 'Panama', 'PA', 0, 0),
        (169, 'Papua New Guinea', 'PG', 0, 0),
        (170, 'Paraguay', 'PY', 0, 0),
        (171, 'Peru', 'PE', 0, 0),
        (172, 'Philippines', 'PH', 0, 0),
        (173, 'Poland', 'PL', 0, 0),
        (174, 'Portugal', 'PT', 0, 0),
        (175, 'Puerto Rico', 'PR', 0, 0),
        (176, 'Qatar', 'QA', 0, 0),
        (177, 'Reunion', 'RE', 0, 0),
        (178, 'Romania', 'RO', 0, 0),
        (179, 'Russian Federation', 'RU', 0, 0),
        (180, 'Rwanda', 'RW', 0, 0),
        (181, 'Saint Barthelemy', 'BL', 0, 0),
        (182, 'Saint Helena, Ascension and Tristan Da Cunha', 'SH', 0, 0),
        (183, 'Saint Kitts and Nevis', 'KN', 0, 0),
        (184, 'Saint Lucia', 'LC', 0, 0),
        (185, 'Saint Martin (French Part)', 'MF', 0, 0),
        (186, 'Saint Pierre and Miquelon', 'PM', 0, 0),
        (187, 'Saint Vincent and The Grenadines', 'VC', 0, 0),
        (188, 'Samoa', 'WS', 0, 0),
        (189, 'San Marino', 'SM', 0, 0),
        (190, 'Sao Tome and Principe', 'ST', 0, 0),
        (191, 'Saudi Arabia', 'SA', 0, 0),
        (192, 'Senegal', 'SN', 0, 0),
        (193, 'Serbia', 'RS', 0, 0),
        (194, 'Seychelles', 'SC', 0, 0),
        (195, 'Sierra Leone', 'SL', 0, 0),
        (196, 'Singapore', 'SG', 0, 0),
        (198, 'Slovakia', 'SK', 0, 0),
        (199, 'Slovenia', 'SI', 0, 0),
        (200, 'Solomon Islands', 'SB', 0, 0),
        (201, 'Somalia', 'SO', 0, 0),
        (202, 'South Africa', 'ZA', 0, 0),
        (204, 'Spain', 'ES', 0, 0),
        (205, 'Sri Lanka', 'LK', 0, 0),
        (206, 'Sudan', 'SD', 0, 0),
        (207, 'Suriname', 'SR', 0, 0),
        (208, 'Swaziland', 'SZ', 0, 0),
        (209, 'Sweden', 'SE', 0, 0),
        (210, 'Switzerland', 'CH', 0, 0),
        (211, 'Syrian Arab Republic', 'SY', 0, 0),
        (212, 'Taiwan, Province of China', 'TW', 0, 0),
        (213, 'Tajikistan', 'TJ', 0, 0),
        (214, 'Tanzania, United Republic of', 'TZ', 0, 0),
        (215, 'Thailand', 'TH', 0, 0),
        (216, 'Timor-Leste', 'TL', 0, 0),
        (217, 'Togo', 'TG', 0, 0),
        (218, 'Tokelau', 'TK', 0, 0),
        (219, 'Tonga', 'TO', 0, 0),
        (220, 'Trinidad and Tobago', 'TT', 0, 0),
        (221, 'Tunisia', 'TN', 0, 0),
        (222, 'Turkey', 'TR', 0, 0),
        (223, 'Turkmenistan', 'TM', 0, 0),
        (224, 'Turks and Caicos Islands', 'TC', 0, 0),
        (225, 'Tuvalu', 'TV', 0, 0),
        (226, 'Uganda', 'UG', 0, 0),
        (227, 'Ukraine', 'UA', 0, 0),
        (228, 'United Arab Emirates', 'AE', 0, 0),
        (229, 'United Kingdom', 'GB', 2, 0),
        (230, 'United States', 'US', 3, 0),
        (231, 'United States Minor Outlying Islands', 'UM', 0, 0),
        (232, 'Uruguay', 'UY', 0, 0),
        (233, 'Uzbekistan', 'UZ', 0, 0),
        (234, 'Vanuatu', 'VU', 0, 0),
        (235, 'Venezuela, Bolivarian Republic of', 'VE', 0, 0),
        (236, 'Viet Nam', 'VN', 0, 0),
        (237, 'Virgin Islands, British', 'VG', 0, 0),
        (238, 'Virgin Islands, U.S.', 'VI', 0, 0),
        (239, 'Wallis and Futuna', 'WF', 0, 0),
        (241, 'Yemen', 'YE', 0, 0),
        (242, 'Zambia', 'ZM', 0, 0),
        (243, 'Zimbabwe', 'ZW', 0, 0);";

        // DB::raw($sql);
        DB::unprepared($sql);
        // return $sql;

    }
}
